# 7.- Arreglos con NUMPY

En este capítulo aprenderás a utilizar algunas cualidades básicas de NumPy (Numerical Python).
NumPy es una de las librerías más populares de Python, ya que puede procesar listas de múltiples
dimensiones

## 7.2.- Arreglo de Datos

Como en la sección anterior, invocaremos a la librería NumPy como np

In [1]:
import numpy as np

Armemos un arreglo de todos los factoriales del 1 al 6

In [2]:
factorial = np.array([1, 2, 6, 24, 12, 720])

Verifica el tipo de objeto que generamos

In [3]:
factorial
type(factorial)

numpy.ndarray

La función array copia automáticamente las dimensiones del argumento. Por ejemplo, el siguiente arreglo (array) está formado por tres filas y dos columnas.

In [4]:
np.array([[3, 4], [5, 6], [7, 8]])

array([[3, 4],
       [5, 6],
       [7, 8]])

#### Por tu cuenta

Arma un arreglo de una dimensión desde una compresnidón de lista que produce todos los números nones del 1 al 30

In [5]:
array_num = np.array([i for i in range(1, 30, 2)])
array_num

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

### 7.2.2 - Atributos de Arreglos

En esta sección usaremos los siguientes 2 arreglos

enteros = np.array([[9,10,11,12],[8,7,6,5]])

flotantes=np.array([[9**(1/2),10**(1/2),3.33,],[10/3,3.4,3.03]])

In [6]:
enteros = np.array([[9, 10, 11, 12], [8, 7, 6, 5]])
flotantes = np.array([[9 ** (1 / 2), 10 ** (1 / 2), 3.33, ], [10 / 3, 3.4, 3.03]])

In [7]:
enteros.dtype
flotantes.dtype

dtype('float64')

Checa el tipo de elemento con dtype

In [8]:
enteros.dtype


dtype('int32')

In [9]:
flotantes.dtype


dtype('float64')

Revisa que puedes ver dimensione con ndim y forma con shape del arreglo

In [10]:
enteros.ndim
enteros.shape

(2, 4)

In [11]:
flotantes.ndim
flotantes.shape

(2, 3)

Size y itemsize te permite conocer el numero de elemntos y de bytes para almacenar

In [12]:
enteros.itemsize

4

Se puede iterar facilmente a través de un arreglo

In [13]:
for fila in flotantes:
    for columna in fila:
        print(columna, end=", ")
        print()

3.0, 
3.1622776601683795, 
3.33, 
3.3333333333333335, 
3.4, 
3.03, 


#### Por tu cuenta

Para el arreglo que armaste en el "Por tu cuenta" previo, checa el numero de dmiensiones y forma del arreglo

In [18]:
array_num.shape

(15,)

In [19]:
array_num.ndim

1

### 7.2.3 - Creando Arreglos desde Rangos

La función arange (una sola R!!!!) nos permite crear rangos de enteros. Crea:

- Un arreglo del 0 al 7
- Un arreglo del 3 al 7
- Un arreglo del 12 al 2 en pasos de 3 en 3 (si, en orden inverso)

In [16]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [17]:
np.arange(3, 8)

array([3, 4, 5, 6, 7])

In [21]:
np.arange(12, 2, -3)

array([12,  9,  6,  3])

Tambien se pueden usar tamaños de paso no enteros. Crea un arreglo con linspace de 0 al 1 que vaya de .25 en .25

In [23]:
np.linspace(0.0, 1.0, num=5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

Y se puede cambiar la forma del arreglo con reshape. Crea un arreglo con arange que vaya del 21 al 1 en orden inverso, y luego dale forma de matriz de 4x5

In [28]:
np.arange(21, 1, -1).reshape(4, 5)

array([[21, 20, 19, 18, 17],
       [16, 15, 14, 13, 12],
       [11, 10,  9,  8,  7],
       [ 6,  5,  4,  3,  2]])

Checate que si el arreglo tiene 1000 o más elementos, numpy no muestra la totalidad de los datos. Generaun arreglo de 0 a 9999 y dale forma de 5 x 2000

In [29]:
np.arange(0, 10000).reshape(5, 2000)

array([[   0,    1,    2, ..., 1997, 1998, 1999],
       [2000, 2001, 2002, ..., 3997, 3998, 3999],
       [4000, 4001, 4002, ..., 5997, 5998, 5999],
       [6000, 6001, 6002, ..., 7997, 7998, 7999],
       [8000, 8001, 8002, ..., 9997, 9998, 9999]])

#### Por tu cuenta

Usa la función arange para crear una rreglo de 20 enteros pares del 42 al 80, y luego rearmalo en una matriz de 4x5

In [35]:
np.arange(42, 81, 2).reshape(4, 5)

array([[42, 44, 46, 48, 50],
       [52, 54, 56, 58, 60],
       [62, 64, 66, 68, 70],
       [72, 74, 76, 78, 80]])

### 7.2.4 - ¿Que tan más rapido es un arreglo?

Usa la magia %timeit y la librería random para crear una comprensión de lista que simule un tiro de dao 6000000 de veces y medir su tiempo

In [38]:
import random as rnd
%timeit tiros = [rnd.randint(0,7) for i in range(0,6000000)]


5.14 s ± 186 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [37]:
%timeit t = np.random.randint(1,7,6000000)

64 ms ± 5.46 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


Ahora usa %timeit para medir el tiempo de un tiro de dado 6000000 de veces pero hecho con arreglo

#### Por tu cuenta

Usa %timeit para ver que es mas rapido - una lista que sume todos los enteros del 0 al 9 999 999 o un arreglo que haga lo mismo con el metodo sum

In [42]:
suma_num_list = list(i for i in range(0, 9999999))
%timeit sum(suma_num_list)

327 ms ± 4.98 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [45]:
suma = np.arange(0, 9999999)
%timeit sum(suma)

<magic-timeit>:1: RuntimeWarning: overflow encountered in scalar add


898 ms ± 5.99 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


## 7.3.- Operaciones con Arreglos

Arma un arreglo de todos los pares del 2 al 15.

- Sumale 1 al arreglo
- Multiplicalo por 3
- Sacale raiz cuadrada

In [48]:
lista1 = np.arange(2, 16, 2)

In [49]:
lista1 + 1

array([ 3,  5,  7,  9, 11, 13, 15])

In [50]:
lista1 * 3

array([ 6, 12, 18, 24, 30, 36, 42])

Al mismo arreglo, aplicale un +=10

In [51]:
lista1 += 10
lista1

array([12, 14, 16, 18, 20, 22, 24])

Arma un arreglo (lista1) que vaya del 2 al 18 de 3 en 3, y otro arreglo (lista2) usando linspace que vaya del -2 al 20 dividido en 6 numeros

- Resta lista1 de lista2
- divide lista2 entre lista1

In [57]:
lista1 = np.arange(2, 18, 3)
lista1

array([ 2,  5,  8, 11, 14, 17])

In [59]:
lista2 = np.linspace(-2, 20, num=6)
lista2

array([-2. ,  2.4,  6.8, 11.2, 15.6, 20. ])

In [60]:
lista2 - lista1

array([-4. , -2.6, -1.2,  0.2,  1.6,  3. ])

In [61]:
lista2 / lista1

array([-1.        ,  0.48      ,  0.85      ,  1.01818182,  1.11428571,
        1.17647059])

También puedes comparar los arreglos

#### Por tu cuenta

Crea un arreglo de los valores que vayan del 1 al 5, y luego elvealo al cuadrado usando **

In [62]:
np.arange(1, 6) ** 2

array([ 1,  4,  9, 16, 25])

### 7.3.2.- Métodos de Cálculo

Considera el siguiente arreglo 

ventas=np.array( [[554,606,710,851],[1244,898,416,1763],
 [841,655,1105,1067]])


In [4]:
import numpy as np

ventas = np.array([[554, 606, 710, 851], [1244, 898, 416, 1763],
                   [841, 655, 1105, 1067]])

Podemos usar métodos para calcular la sum, min, max, mean, std, var. 

In [5]:
ventas.min()

416

In [6]:
ventas.max(
)

1763

In [7]:
ventas.sum()

10710

In [8]:
ventas.std()

350.56656524355924

In [10]:
ventas.var()

122896.91666666667

También es posible hacerlo por filas y columnas. Checa como se hace con axis = 1 y 0

In [14]:
ventas.mean(axis=0)
#prom de cada una de3 las columnas

array([ 879.66666667,  719.66666667,  743.66666667, 1227.        ])

In [15]:
ventas.mean(axis=1)
#prom, de las filas

array([ 680.25, 1080.25,  917.  ])

#### Por tu cuenta

Usa el generador de numeros aleatoreos de numpy (np.random.randint) para crear una rreglo de 12 calificaciones aleatorias del 60 al 100, y luego dale forma en una matriz de 3x4. Calcula el promedio de todas las calificaciones, el promedio de cada columna y de cada fila. 

In [94]:
calificaciones =np.array([(np.random.randint(59,101)) for i in range(1,13) ]).reshape(3,4)


[[ 82  65  92  78]
 [ 94  63  68 100]
 [ 64  63  74  88]]


In [95]:
#promedio columna
calificaciones.mean(axis=0)

array([80.        , 63.66666667, 78.        , 88.66666667])

In [96]:
#prom fila
calificaciones.mean(axis=1)

array([79.25, 81.25, 72.25])

In [98]:
cal = np.random.randint(60,100,12).reshape(3,4)


array([[65, 92, 84, 65],
       [74, 77, 63, 70],
       [74, 92, 97, 90]])

## 7.4.- Indexando y Cortando arreglos

Crea el arreglo

ventas=np.array ([[ 554, 606, 710, 851],
 [1244, 898, 416, 1763],
 [ 841, 655, 1105, 1067]])
 
 - Selecciona el item 2,1
 - Selecciona el item 1,3
 - Selecciona la fila 1

In [100]:
ventas=np.array ([[ 554, 606, 710, 851],
 [1244, 898, 416, 1763],
 [ 841, 655, 1105, 1067]])

In [101]:
ventas[1,0]

1244

Solicita las filas con índices 0 y 1

In [103]:
ventas[0:2]

array([[ 554,  606,  710,  851],
       [1244,  898,  416, 1763]])

Ahora para solicitar las filas con indices 1 y 2

In [105]:
ventas[1:3]

array([[1244,  898,  416, 1763],
       [ 841,  655, 1105, 1067]])

Quieres solo los elementos de la primera columna?

In [106]:
ventas[:,0]

array([ 554, 1244,  841])

Que la las columnas con indices 0 y 2?

In [107]:
ventas[:,[0,2]]

array([[ 554,  710],
       [1244,  416],
       [ 841, 1105]])

 #### Por tu cuenta

Dado el siguiente arreglo

array([[1,2,3,4,5],
     [6,7,8,9,10],
     [11,12,13,14,15]])

- Selecciona la segunda fila
- Selecciona la primera y tercera fila
- Selecciona las tres columnas de enmedio

In [111]:
v= np.array([[1,2,3,4,5],
     [6,7,8,9,10],
     [11,12,13,14,15]])

In [114]:
v[1]

array([ 6,  7,  8,  9, 10])

In [118]:
v[[0,2]]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [121]:
ventas[:,1:4]

array([[ 606,  710,  851],
       [ 898,  416, 1763],
       [ 655, 1105, 1067]])

### 7.4.2.- Transponer

Con **reshape** puedes producir una copia superficial del arreglo con una nueva dimension. 

ventas = np.array([[ 500, 600, 550, 800],
 [1200, 800, 400,1000]])

Usa el arreglo anterior para darle dimension de 1x8

In [127]:
ventas = np.array([[ 500, 600, 550, 800],
 [1200, 800, 400,1000]])

In [124]:
ventas.reshape(1,8)

array([[ 500,  600,  550,  800, 1200,  800,  400, 1000]])

El metodo **resize** modifica la forma del original (no crea copia)

In [126]:
ventas.resize(1,8)
ventas

array([[ 500,  600,  550,  800, 1200,  800,  400, 1000]])

Y **transpose** rapidamente le da la vuelta a filas y columnas, este se hace aplicando el atributo T, que no modifica el original, solo una vista.

In [128]:
ventas.T

array([[ 500, 1200],
       [ 600,  800],
       [ 550,  400],
       [ 800, 1000]])

## 7.5.- Pandas - Series

Vamos a usar estos datos para Series - tiempo_web = pd.Series([160,256,98,108])

Este es el tiempo que invierten en videojuegos 4 estudiantes

In [129]:
import pandas as pd

In [130]:
time_web = pd.Series([160,256,98,100])

In [131]:
time_web

0    160
1    256
2     98
3    100
dtype: int64

Para crear una serie con el mismo elemento

In [132]:
pd.Series(3.1416,range(5))

0    3.1416
1    3.1416
2    3.1416
3    3.1416
4    3.1416
dtype: float64

Acceder a un elemento es facil

In [133]:
time_web[2]

98

Series tiene acceso a los mismos metodos que arreglos para estadistica descriptiva

In [134]:
time_web.mean()

153.5

Tambien, todo esto se puede resumir con **describe**

In [135]:
time_web.describe()

count      4.000000
mean     153.500000
std       74.141756
min       98.000000
25%       99.500000
50%      130.000000
75%      184.000000
max      256.000000
dtype: float64

También podemos personalizar los indices de series a traves de index

['Laura','Daniel','Alberto','Eva'] 

Asigna esos nombres

In [137]:
time_web = pd.Series([160,256,98,100],index=['Laura','Daniel','Alberto','Eva'])

In [138]:
time_web

Laura      160
Daniel     256
Alberto     98
Eva        100
dtype: int64

O puedes usar un diccionario para eso:

C:\Users\crist\AppData\Local\Temp\ipykernel_34232\3378049827.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  time_web[2]


98

Puedes llamar a los elementos personalizados

In [143]:
time_web["Alberto"]

98

Tambien se pueden llamar como atributos

In [144]:
time_web.Eva  

100

#### Por tu cuenta

Usa el generador aleatorio de NumPy (np.random.randint) para generar 6 calificaciones del 60 al 100 y guardarlos en una serie. 

A continuación arma las siguientes tareas:

- Convierte el arreglo en una serie llamada calificacion
- Determina la min, max y promedio
- Produce TODAS las estadisticas descriptivas

In [147]:
calificaciones =pd.Series( np.random.randint(60,100,12))
calificaciones

0     84
1     61
2     76
3     76
4     89
5     64
6     93
7     90
8     88
9     82
10    93
11    75
dtype: int32

In [151]:
calificaciones.mean()

80.91666666666667

In [150]:
calificaciones.min()

61

In [152]:
calificaciones.max()

93

In [153]:
calificaciones.describe()

count    12.000000
mean     80.916667
std      10.731926
min      61.000000
25%      75.750000
50%      83.000000
75%      89.250000
max      93.000000
dtype: float64

## 7.6.- Pandas - DataFrames

##### Crear un Dataframe de un diccionario

Agarra este diccionario y conviertelo en un dataframe

 reg_peso = {'Vanesa':[68,67,66,65],'Kevin':[89,89,90,88],
 'Fernanda':[59,60,60,62],'Patricia':[70,68,67,65]}

In [154]:
 reg_peso = {'Vanesa':[68,67,66,65],'Kevin':[89,89,90,88],
 'Fernanda':[59,60,60,62],'Patricia':[70,68,67,65]}

In [155]:
peso  =pd.DataFrame(reg_peso)

In [156]:
peso

Vanesa  Kevin  Fernanda  Patricia
0      68     89        59        70
1      67     89        60        68
2      66     90        60        67
3      65     88        62        65

##### El atributo Index

Añade los siguientes indices personalizados

peso.index = ['Mes 1','Mes 2','Mes 3','Mes 4']

In [157]:
peso.index = ['Mes 1','Mes 2','Mes 3','Mes 4']

In [158]:
peso

Vanesa  Kevin  Fernanda  Patricia
Mes 1      68     89        59        70
Mes 2      67     89        60        68
Mes 3      66     90        60        67
Mes 4      65     88        62        65

##### Accesar Columnas

Selecciona la información de Fernanda

In [159]:
peso['Fernanda']

Mes 1    59
Mes 2    60
Mes 3    60
Mes 4    62
Name: Fernanda, dtype: int64

Selecciona la de Patricia pero como atributo

In [160]:
peso.Patricia

Mes 1    70
Mes 2    68
Mes 3    67
Mes 4    65
Name: Patricia, dtype: int64

##### Loc y iloc

Selecciona la información del Mes1 usando Loc

In [161]:
peso.loc['Mes 1']

Vanesa      68
Kevin       89
Fernanda    59
Patricia    70
Name: Mes 1, dtype: int64

Ahora solo la fila 1 usando iloc

In [162]:
peso.iloc[1]

Vanesa      67
Kevin       89
Fernanda    60
Patricia    68
Name: Mes 2, dtype: int64

Ahora del Mes 1 al Mes 3 usando loc

In [166]:
peso.loc['Mes 1':'Mes 3']

Vanesa  Kevin  Fernanda  Patricia
Mes 1      68     89        59        70
Mes 3      66     90        60        67

Saca filas especificas (mes 1 y 3) usando loc

In [167]:
peso.loc[['Mes 1','Mes 3']]

Vanesa  Kevin  Fernanda  Patricia
Mes 1      68     89        59        70
Mes 3      66     90        60        67

Y ahora los Meses 2 y 3 de Vanesa y Patricia solamente con loc

In [169]:
peso.loc['Mes 1':'Mes 3', ['Vanesa','Patricia']]

Vanesa  Patricia
Mes 1      68        70
Mes 2      67        68
Mes 3      66        67

##### Indices Booleanos

Dime los pesos mayores a 70kg en la tabla

In [170]:
peso[peso>70]

Vanesa  Kevin  Fernanda  Patricia
Mes 1     NaN     89       NaN       NaN
Mes 2     NaN     89       NaN       NaN
Mes 3     NaN     90       NaN       NaN
Mes 4     NaN     88       NaN       NaN

Y ahora los pesos mayores a 65kg y menores a 80kg

In [172]:
peso[(peso>65) & (peso<80)]

Vanesa  Kevin  Fernanda  Patricia
Mes 1    68.0    NaN       NaN      70.0
Mes 2    67.0    NaN       NaN      68.0
Mes 3    66.0    NaN       NaN      67.0
Mes 4     NaN    NaN       NaN       NaN

##### Accesar una celda especifica de un Dataframe

Que pasa si solo queremos cuanto pesaba Patricia en el mes 3? Usa at

In [173]:
peso.at['Mes 3', 'Patricia']

67

Resulta que Kevin en realidad pesaba 85kg en el mes 4, cambia su valor usando at

In [174]:
peso.at['Mes 4','Kevin']= 85
peso

Vanesa  Kevin  Fernanda  Patricia
Mes 1      68     89        59        70
Mes 2      67     89        60        68
Mes 3      66     90        60        67
Mes 4      65     85        62        65

##### Estádistica descriptiva

Puedes usar el metodo **Describe** para sacar todas las estadisticas del dataframe

In [175]:
peso.describe()

Vanesa      Kevin   Fernanda   Patricia
count   4.000000   4.000000   4.000000   4.000000
mean   66.500000  88.250000  60.250000  67.500000
std     1.290994   2.217356   1.258306   2.081666
min    65.000000  85.000000  59.000000  65.000000
25%    65.750000  88.000000  59.750000  66.500000
50%    66.500000  89.000000  60.000000  67.500000
75%    67.250000  89.250000  60.500000  68.500000
max    68.000000  90.000000  62.000000  70.000000

También puedes cambiar la cantidad de decimales usando **Precision**

In [187]:
pd.set_option('precision',1
              )

OptionError: Pattern matched multiple keys

In [177]:
peso.describe()

Vanesa      Kevin   Fernanda   Patricia
count   4.000000   4.000000   4.000000   4.000000
mean   66.500000  88.250000  60.250000  67.500000
std     1.290994   2.217356   1.258306   2.081666
min    65.000000  85.000000  59.000000  65.000000
25%    65.750000  88.000000  59.750000  66.500000
50%    66.500000  89.000000  60.000000  67.500000
75%    67.250000  89.250000  60.500000  68.500000
max    68.000000  90.000000  62.000000  70.000000

Y también se pueden aplicar los metodos de estadistica descriptiva individuales como mean

In [188]:
peso.mean()

Vanesa      66.50
Kevin       88.25
Fernanda    60.25
Patricia    67.50
dtype: float64

##### Transponer

Si quisieramos voltear el dataframe, tendríamos que hacer el método T

In [189]:
peso.T

Mes 1  Mes 2  Mes 3  Mes 4
Vanesa       68     67     66     65
Kevin        89     89     90     85
Fernanda     59     60     60     62
Patricia     70     68     67     65

Y ahora eso nos ayudaría a sacar los estadísticos para los meses en vez de para las personas

In [190]:
peso.T.mean()


Mes 1    71.50
Mes 2    71.00
Mes 3    70.75
Mes 4    69.25
dtype: float64

Y el peso promedio por mes de nuestra gente

In [192]:
peso.T.describe()

Mes 1      Mes 2      Mes 3     Mes 4
count   4.00000   4.000000   4.000000   4.00000
mean   71.50000  71.000000  70.750000  69.25000
std    12.60952  12.516656  13.200379  10.59481
min    59.00000  60.000000  60.000000  62.00000
25%    65.75000  65.250000  64.500000  64.25000
50%    69.00000  67.500000  66.500000  65.00000
75%    74.75000  73.250000  72.750000  70.00000
max    89.00000  89.000000  90.000000  85.00000

##### Ordenar el Dataframe

Ahora vamos a arreglar el dataframe por fila, con los indices en orden descendente

In [193]:
peso.sort_index(ascending=False)

Vanesa  Kevin  Fernanda  Patricia
Mes 4      65     85        62        65
Mes 3      66     90        60        67
Mes 2      67     89        60        68
Mes 1      68     89        59        70

peso.Las columnas en orden ascendente

In [194]:
peso.sort_index(axis=1)

Fernanda  Kevin  Patricia  Vanesa
Mes 1        59     89        70      68
Mes 2        60     89        68      67
Mes 3        60     90        67      66
Mes 4        62     85        65      65

Y también se vale ordenar los valores según una fila o columna especifica.  El siguiente código ordena de forma descendente los datos del DataFrame con respecto
a los valores del Mes 1.

In [195]:
peso.loc['Mes 1'].sort_values(ascending=False)

Kevin       89
Patricia    70
Vanesa      68
Fernanda    59
Name: Mes 1, dtype: int64